// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ponytail: migrate needs session/direct (not pgbouncer :6543); app runtime still uses DATABASE_URL via adapter
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
